[package]
name = "gcsf"
description = "Filesystem based on Google Drive"
version = "0.1.2"
authors = ["Sergiu Puscas <srg.pscs@gmail.com>"]
license = "MIT"

[dependencies]
clap = { version = "2.31.2", features = ["yaml"]}
ctrlc = "3.1.0"
failure = "0.1.1"
fuse = "0.3.1"
# google-drive3 = "1.0.7+20171201"
google-drive3-fork = "1.0.10"
id_tree = "1.2.0"
lazy_static = "1.0"
libc = "0.2.40"
log = "0.4.1"
lru_time_cache = "0.8.0"
maplit = "1.0.1"
mime-sniffer = "0.1.2"
pretty_env_logger = "0.2.2"
rand = "0.4.2"
serde = "1.0.39"
serde_derive = "1.0.39"
serde_json = "1.0.15"
time = "0.1.39"
yup-oauth2 = "1.0.7"

# These versions required by google-drive3
hyper = "0.10"
hyper-rustls = "0.6"
