[package]
name = "gcsf"
version = "0.1.0"
authors = ["Sergiu Puscas <srg.pscs@gmail.com>"]

[dependencies]
google-drive3 = "*"
id_tree = "1.2.0"
maplit = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
hyper = "*"
hyper-rustls = "*"
yup-oauth2 = "*"
fuse = "*"
time = "*"
log = "0.4"
pretty_env_logger = "0.2.1"
