[package]
name = "gcsf"
version = "0.1.0"
authors = ["Sergiu Puscas <srg.pscs@gmail.com>"]
license = "MIT"

[dependencies]
fuse = "0.3.1"
google-drive3 = "1.0.7+20171201"
failure = "0.1.1"
id_tree = "1.2.0"
libc = "0.2.40"
log = "0.4.1"
maplit = "1.0.1"
pretty_env_logger = "0.2.2"
serde = "1.0.39"
serde_derive = "1.0.39"
serde_json = "1.0.15"
time = "0.1.39"
yup-oauth2 = "1.0.7"
ctrlc = "3.1.0"

# These versions required by google-drive3
hyper = "0.10"
hyper-rustls = "0.6"
